[nginx]
18.195.215.102 ansible_user=ec2-user letsencrypt_email=leksval@yahoo.com domain_name=samochodyprawiezafree.ml


[stat_server]
52.59.249.5 ansible_user=ec2-user

[app_nodes]
52.58.160.75 ansible_user=ec2-user
52.58.160.75 ansible_user=ec2-user

